"""create users table

Revision ID: 74409721a129
Revises: 
Create Date: 2026-03-31 07:50:41.386382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74409721a129'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usertypes_id'), 'usertypes', ['id'], unique=False)
    op.add_column('users', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'usertypes', ['user_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_type_id')
    op.drop_index(op.f('ix_usertypes_id'), table_name='usertypes')
    op.drop_table('usertypes')
    # ### end Alembic commands ###
